In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [3]:
df=pd.read_csv('dataset/gurgaon_properties.csv')

In [4]:
df.tail()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3956,3 BHK Flat in Sector 103 Gurgaon,flat,indiabulls centrum park,1.90,5681.0,3344.0,Carpet area: 3344 (310.67 sq.m.),3,4,3+,"pooja room,study room,servant room,others","Sector 103 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'HUDA Market, Sector 1...",Located in the popular residential address of ...,"['4 Wardrobe', '1 Water Purifier', '10 Fan', '...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
3957,3 BHK Flat in Sector 36 Sohna,flat,signature global park 4,0.72,6660.0,1081.0,Super Built up area 1081(100.43 sq.m.),3,2,3,not available,"Sector 36 Sohna, Gurgaon, Haryana",3.0,NaN,Under Construction,NaN,Residential apartment for sell.Located in sect...,[],NaN,NaN
3958,2 Bedroom House for sale in Shivpuri,house,independent,2.00,11111.0,1800.0,Plot area 200(167.23 sq.m.),2,2,1,not available,"Gurgaon Sector -7, Shivpuri, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Arya...",Interested to sell independent house/villa.Pla...,"['2 Fan', 'No AC', 'No Bed', 'No Chimney', 'No...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
3959,2 BHK Flat in Sector 90 Gurgaon,flat,shree vardhman flora,0.75,5769.0,1300.0,Carpet area: 1300 (120.77 sq.m.),2,2,3,not available,"Sector 90, Sector 90 Gurgaon, Gurgaon, Haryana",8.0,North-East,undefined,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",Best in class property available at sector 90 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Amenities5 out of 5'..."
3960,4 Bedroom House for sale in Laxman Vihar Phase 2,house,independent,0.92,15257.0,603.0,Plot area 67(56.02 sq.m.),4,4,3,others,"2676, Laxman Vihar Phase 2, Gurgaon, Haryana",4.0,East,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shre...",Because all connectivity are available all tra...,"['2 Fan', '10 Light', '3 Wardrobe', 'No AC', '...",NaN,NaN

In [5]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
113,3 BHK Flat in Sector 37C Gurgaon,flat,corona optus,1.22,6912.0,1765.0,Super Built up area 1765(163.97 sq.m.)Built Up...,3,4,3,not available,"501, Sector 37C Gurgaon, Gurgaon, Haryana",5.0,South-East,1 to 5 Year Old,"['The Esplanade Mall', 'Gurugram Road', 'Delhi...",This lovely 3 bhk apartment/flat in sector 37c...,NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
123,4 BHK Flat in Sector 83 Gurgaon,flat,vatika gurgaon,1.33,5564.0,2390.0,Super Built up area 2390(222.04 sq.m.)Carpet a...,4,4,3,servant room,"Sector 83 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Available for sale 4bhk and servant room lower...,NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'M...","['Green Area5 out of 5', 'Construction4.5 out ..."
647,2 BHK Flat in DLF Phase 4,flat,dlf regency park,1.91,16608.0,1150.0,Carpet area: 1150 (106.84 sq.m.),2,2,2,not available,"DLF Phase 4, Gurgaon, Haryana",11.0,NaN,0 to 1 Year Old,"['Sector 42-43 metro station', 'Dlf phase 1 me...",A fully furnished luxury 2 bhk for sale with 4...,"['1 Water Purifier', '3 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."
2704,4 BHK Flat in Sector 56 Gurgaon,flat,meditech apartment,2.45,8166.0,3000.0,Super Built up area 3000(278.71 sq.m.)Built Up...,4,4,3+,others,"Sector 56 Gurgaon, Sector 56 Gurgaon, Gurgaon,...",1.0,West,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...",Brokers please excuse. Looking for a 4 bhk pro...,"['6 Fan', '1 Exhaust Fan', '3 Geyser', '1 Chim...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
3111,3 BHK Flat in Sector 85 Gurgaon,flat,orris carnation residency,0.88,5952.0,1478.0,Super Built up area 1485(137.96 sq.m.),3,3,1,not available,"Sector 85 Gurgaon, Gurgaon, Haryana",1.0,South,1 to 5 Year Old,"['Omaxe Celebration Mall within reach', 'Nearb...",Azzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area4 out of 5', 'Construction4 out of..."

In [6]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [7]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,Sector 66,3.98,18090.0,2200.0,Super Built up area 2200(204.39 sq.m.),3,4,3+,servant room,"Sector 66 Gurgaon, Gurgaon, Haryana",2.0,South-East,5 to 10 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Beautiful two side open property, facing kids ...","['6 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ..."
1,2 BHK Flat in Sector 62 Gurgaon,flat,emaar digihomes,Sector 62,2.15,14257.0,1508.0,Carpet area: 1508 (140.1 sq.m.),2,2,3,not available,"3301, Sector 62 Gurgaon, Gurgaon, Haryana",31.0,NaN,Under Construction,"['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",This is your chance to own a 2 bhk residential...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Connectivity4 out of 5', 'Lifestyle5 out of ..."
2,3 BHK Flat in Sector 65 Gurgaon,flat,m3m heights,Sector 65,2.44,13300.0,1835.0,Super Built up area 1828(169.83 sq.m.),3,3,2,not available,"Sector 65 Gurgaon, Gurgaon, Haryana",7.0,NaN,May 2024,"['Rapid Metro Sector 56', 'M3m 65th Avenue Mal...",Gurgaon sector 65 is a prime location in gurga...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,3 BHK Flat in Nirvana Country,flat,the close south,Nirvana Country,3.10,12444.0,2491.0,Super Built up area 2491(231.42 sq.m.)Built Up...,3,4,3+,servant room,"4th, Nirvana Country, Gurgaon, Haryana",4.0,North-East,5 to 10 Year Old,"['Fresco Market', 'Emerald Plaza', 'Tagore Pub...",The close south is one of gurgaon's most sough...,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."
4,3 BHK Flat in Sector 33 Gurgaon,flat,unitech the residences,Sector 33,1.55,9872.0,1570.0,Super Built up area 1570(145.86 sq.m.),3,4,1,servant room,"101, Sector 33 Gurgaon, Gurgaon, Haryana",1.0,South,1 to 5 Year Old,"['Huda Metro Station', 'Raheja Mall', 'Delhi G...",Central garden full view.\nGood ventilation.\n...,"['7 Fan', '7 Light', '3 Wardrobe', 'No AC', 'N...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area5 out of 5', 'Amenities3 out of 5'..."

In [8]:
df['sector']=df['sector'].str.lower()

In [9]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,sector 66,3.98,18090.0,2200.0,Super Built up area 2200(204.39 sq.m.),3,4,3+,servant room,"Sector 66 Gurgaon, Gurgaon, Haryana",2.0,South-East,5 to 10 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Beautiful two side open property, facing kids ...","['6 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ..."
1,2 BHK Flat in Sector 62 Gurgaon,flat,emaar digihomes,sector 62,2.15,14257.0,1508.0,Carpet area: 1508 (140.1 sq.m.),2,2,3,not available,"3301, Sector 62 Gurgaon, Gurgaon, Haryana",31.0,NaN,Under Construction,"['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",This is your chance to own a 2 bhk residential...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Connectivity4 out of 5', 'Lifestyle5 out of ..."
2,3 BHK Flat in Sector 65 Gurgaon,flat,m3m heights,sector 65,2.44,13300.0,1835.0,Super Built up area 1828(169.83 sq.m.),3,3,2,not available,"Sector 65 Gurgaon, Gurgaon, Haryana",7.0,NaN,May 2024,"['Rapid Metro Sector 56', 'M3m 65th Avenue Mal...",Gurgaon sector 65 is a prime location in gurga...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,3 BHK Flat in Nirvana Country,flat,the close south,nirvana country,3.10,12444.0,2491.0,Super Built up area 2491(231.42 sq.m.)Built Up...,3,4,3+,servant room,"4th, Nirvana Country, Gurgaon, Haryana",4.0,North-East,5 to 10 Year Old,"['Fresco Market', 'Emerald Plaza', 'Tagore Pub...",The close south is one of gurgaon's most sough...,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."
4,3 BHK Flat in Sector 33 Gurgaon,flat,unitech the residences,sector 33,1.55,9872.0,1570.0,Super Built up area 1570(145.86 sq.m.),3,4,1,servant room,"101, Sector 33 Gurgaon, Gurgaon, Haryana",1.0,South,1 to 5 Year Old,"['Huda Metro Station', 'Raheja Mall', 'Delhi G...",Central garden full view.\nGood ventilation.\n...,"['7 Fan', '7 Light', '3 Wardrobe', 'No AC', 'N...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area5 out of 5', 'Amenities3 out of 5'..."

In [10]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
nirvana country                                               53
sector 70                                                     53
sector 37c                                                    53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
sector 113                                                    43
dlf phase 2                                                   43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
laxman vihar                                                  27
sector 54                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 111                                                    22
dlf phase 3                                                   22
sector 67a                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sector 99                                                     16
sushant lok phase 3                                           16
sector 14                                                     15
sector 63                                                     15
sector 60                                                     15
dlf phase 5                                                   14
sector 3                                                      14
sector 53                                                     14
gwal pahari                                                   14
sector 1 imt manesar                                          14
rajendra park                                                 14
sector 76                                                     14
sector 52                                                     14
laxman vihar phase 2                                          13
sector 46                                                     13
sector 36a                                                    13
sector 39                                                     12
sohna road                                                    12
sector 31                                                     12
sector 93                                                     12
sector 38                                                     12
sector 50                                                     12
uppals southend                                               12
sector 47                                                     11
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 7                                                      10
sector 1a imt manesar                                         10
south city 1                                                   9
sector 4                                                       9
sector 55                                                      9
sector 95a                                                     9
ashok vihar phase 2                                            9
sector 43                                                      8
sector 89 a                                                    8
mehrauli  road                                                 8
sector 40                                                      8
c block sushant lok phase 1                                    8
sector 57                                                      8
malibu town                                                    8
dwarka expressway                                              8
palam vihar extension                                          8
sector 59                                                      8
sector 10a                                                     8
sector 51                                                      7
new colony                                                     7
mianwali colony                                                7
sector 58                                                      7
sector 36 sohna                                                7
sector 26                                                      7
sector 11                                                      7
surat nagar 1                                                  7
sector 5                                                       6
jyoti park                                                     6
jacobpura                                                      6
rajiv nagar                                                    6
ashok vihar                                                    6
sector 1                                                       6
sector 9                                                       5
arjun nagar                                                    5
greenwood city                                                 5
ansal plaza                                                    5
dayanand colony                                                5
subhash nagar                                                  5
new palam vihar                                                5
sushant lok phase 2                                            5
chakkarpur                                                     5
sector 28                                                      5
sector 2                                                       5
sector 80                                                      5
sector 105                                                     5
sector 23a                                                     5
saraswati vihar                                                5
manesar                                                        5
sector 30                                                      5
madanpuri                                                      4
surya vihar                                                    4
sector 17                                                      4
baldev nagar                                                   4
vishnu garden                                                  4
imt manesar                                                    4
sector 12                                                      4
devilal colony                                                 4
dharam colony                                                  4
krishna colony                                                 4
valley view estate                                             4
adarsh nagar                                                   4
new                                                            4
sector 36                                                      4
ravi nagar                                                     4
sector 6                                                       4
bhim nagar                                                     4
sector 45                                                      4
sector 3a                                                      4
bhondsi                                                        4
garhi harsaru                                                  4
suncity                                                        4
sector 12a                                                     4
shivaji nagar                                                  4
shivpuri                                                       4
sector 17a                                                     3
laxmi garden                                                   3
sector 110 a                                                   3
a block sushant lok phase 1                                    3
shakti nagar                                                   3
sector 15                                                      3
gandhi nagar                                                   3
sector 73                                                      3
b block sushant lok phase 1                                    3
sector 23                                                      3
sector 8                                                       3
sector 88b                                                     3
sector 17b                                                     3
sector 27                                                      3
patel nagar                                                    3
maruti kunj                                                    3
mg road                                                        3
prem nagar                                                     3
new palam vihar phase 1                                        2
sector 15 part 1                                               2
sohna  road                                                    2
manohar nagar                                                  2
sector 15 part 2                                               2
surat nagar                                                    2
faridabad road                                                 2
golf course ext road                                           2
block a surya vihar                                            2
sector-2 sohna                                                 2
farukhnagar                                                    2
golf course road                                               2
sector 21                                                      2
mayfield garden                                                2
iffco chowk                                                    2
pratap nagar                                                   2
west rajiv nagar                                               2
daulatabad                                                     2
sector 24                                                      2
bhawani enclave                                                2
hira nagar                                                     2
sector 41                                                      2
, delhi ncr                                                    2
sushant lok                                                    2
bissar                                                         2
samaspur                                                       2
shanti nagar                                                   2
lajpat nagar                                                   2
ambience island                                                2
sheetla colony                                                 2
sector 32                                                      2
sector-11 sohna                                                2
mohan nagar                                                    2
acharya puri                                                   2
new palam vihar phase 2                                        2
rosewood                                                       2
new basti                                                      2
rajiv chowk                                                    2
surat nagar phase 2                                            2
nars                                                           2
sispal vihar                                                   2
shankar vihar                                                  2
ansal's palam vihar                                            1
sector 21a faridabad                                           1
bhora kalan                                                    1
ashok vihar phase i                                            1
laxmna vihar, phase 2                                          1
shivji park colony                                             1
sadar bazar                                                    1
heritage city                                                  1
sector 37a                                                     1
sector 4 urban estate                                          1
v block dlf phase 3                                            1
damdma                                                         1
alipur                                                         1
ravi nager basai road                                          1
hsiidc plot sector 1 imt manesar                               1
sector 37b                                                     1
old delhi road, opp sector-14                                  1
g block dlf city phase 1                                       1
tekchand nagar                                                 1
rattan garden                                                  1
laxman vihar, railway road,                                    1
cyber city                                                     1
kheri                                                          1
huda saraswati vihar                                           1
sultanpur                                                      1
sector-5 sheetla colony                                        1
kanahi                                                         1
sector 13                                                      1
civil l                                                        1
gopal nagar, garhi ghasita, sonipat                            1
naharpur rupa                                                  1
block g sector-57                                              1
khandsa                                                        1
ashok vihar phase 3                                            1
sector 42                                                      1
near khandsa road                                              1
sector 17c                                                     1
om nagar                                                       1
near euro                                                      1
begampur khatola                                               1
sector 5 chowk                                                 1
near pataudi chowk                                             1
park view                                                      1
ats marigold                                                   1
part 3 sector 5                                                1
saroop garden rajendra park                                    1
rajiv colony                                                   1
nirvana country pocket h                                       1
dhankot                                                        1
ram nagar                                                      1
mahalaxmi garden, rajendra place                               1
jacobpura near sadar bazar                                     1
new jyoti park                                                 1
sai kunj                                                       1
vir nagar                                                      1
near nand hospital                                             1
sec 3 bhim vihar part 1 bhimgher kheri                         1
garauli kalan                                                  1
lucknow                                                        1
near sector 1 market                                           1
anand garden, sector-105                                       1
block h ashok vihar phase iii extension                        1
hno 13 sagar enclave sura                                      1
sector-7 hous                                                  1
godrej aria , sector 79 ,                                      1
b1 block sector 57                                             1
devi lal colony gali no 12 gurgaon nr omkar public school      1
new colony, sector 7                                           1
carterpuri village                                             1
sector 9b                                                      1
saraswati enclave                                              1
mahavir pura                                                   1
south city                                                     1
bptp                                                           1
sector-5 sohna                                                 1
bhimgarh kheri phase 3                                         1
udyog vihar phase 1                                            1
urban estate, sector 5                                         1
jat colony,fazilpur/taj nagar road                             1
sector-35 sohna                                                1
pataudi road                                                   1
Name: count, dtype: int64

In [11]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [12]:
a=df['sector'].value_counts()[df['sector'].value_counts()>=3]
df=df[df['sector'].isin(a.index)]

In [13]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 90                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 70                      53
sector 43                      53
sector 37c                     53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 112                     24
sector 24                      24
sector 57                      24
sector 33                      23
sector 88a                     23
sector 14                      23
sector 105                     23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 3                       20
sector 82a                     20
sector 22                      20
sector 78                      19
sector 47                      19
sector 74                      18
gwal pahari                    18
sector 63a                     18
sector 62                      17
sector 91                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 60                      15
sector 53                      14
sector 1 manesar               14
sector 76                      14
sector 55                      14
sector 52                      14
sector 4 phase 2               13
sector 9                       13
sector 46                      13
sector 36a                     13
sector 6                       13
sector 39                      12
sohna road road                12
sector 31                      12
sector 93                      12
sector 38                      12
sector 41                      11
sector 9a                      11
sector 3 phase 3 extension     11
sector 13                      10
sector 1a manesar              10
sector 45                       9
manesar                         9
sector 95a                      9
sector 3 phase 2                9
sector 89 a                     8
sector 8                        8
sector 17                       8
sector 40                       8
c block sector 43               8
sector 23                       8
dwarka expressway               8
sector 2 extension              8
sector 59                       8
sector 10a                      8
sector 51                       7
sector 58                       7
sector 36 sohna road            7
sector 5                        6
sector 21                       6
sector 1                        6
new sector 2                    5
sector 80                       5
sector 23a                      5
sector 30                       5
new                             4
sector 36                       4
sector 3a                       4
sector 12a                      4
sector 17a                      3
sector 110 a                    3
a block sector 43               3
sector 15                       3
sector 73                       3
b block sector 43               3
sector 88b                      3
sector 17b                      3
sector 27                       3
patel nagar                     3
maruti kunj                     3
Name: count, dtype: int64

In [14]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')
df['sector'] = df['sector'].str.replace('sector 3 phase 2','sector 3')
df['sector']=df['sector'].str.replace('sector 3 phase 3 extension','sector 3')

In [15]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
764,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1823,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
1920,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
2395,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN

In [16]:
df.loc[764,'sector'] = 'sector 76'
df.loc[1823,'sector'] = 'sector 90'
df.loc[1920,'sector'] = 'sector 92'
df.loc[2395,'sector'] = 'sector 37'

In [17]:
df[df['sector']=='new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
638,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1449,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1933,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
2839,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2916,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [18]:
df.loc[[638,1449,1933,2839,2916],'sector'] = 'sector 110'

In [19]:
df.shape

(3803, 21)

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,sector 66,3.98,18090.0,2200.0,Super Built up area 2200(204.39 sq.m.),3,4,3+,servant room,"Sector 66 Gurgaon, Gurgaon, Haryana",2.0,South-East,5 to 10 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Beautiful two side open property, facing kids ...","['6 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ..."
1,2 BHK Flat in Sector 62 Gurgaon,flat,emaar digihomes,sector 62,2.15,14257.0,1508.0,Carpet area: 1508 (140.1 sq.m.),2,2,3,not available,"3301, Sector 62 Gurgaon, Gurgaon, Haryana",31.0,NaN,Under Construction,"['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",This is your chance to own a 2 bhk residential...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Connectivity4 out of 5', 'Lifestyle5 out of ..."
2,3 BHK Flat in Sector 65 Gurgaon,flat,m3m heights,sector 65,2.44,13300.0,1835.0,Super Built up area 1828(169.83 sq.m.),3,3,2,not available,"Sector 65 Gurgaon, Gurgaon, Haryana",7.0,NaN,May 2024,"['Rapid Metro Sector 56', 'M3m 65th Avenue Mal...",Gurgaon sector 65 is a prime location in gurga...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,3 BHK Flat in Nirvana Country,flat,the close south,sector 50,3.10,12444.0,2491.0,Super Built up area 2491(231.42 sq.m.)Built Up...,3,4,3+,servant room,"4th, Nirvana Country, Gurgaon, Haryana",4.0,North-East,5 to 10 Year Old,"['Fresco Market', 'Emerald Plaza', 'Tagore Pub...",The close south is one of gurgaon's most sough...,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."
4,3 BHK Flat in Sector 33 Gurgaon,flat,unitech the residences,sector 33,1.55,9872.0,1570.0,Super Built up area 1570(145.86 sq.m.),3,4,1,servant room,"101, Sector 33 Gurgaon, Gurgaon, Haryana",1.0,South,1 to 5 Year Old,"['Huda Metro Station', 'Raheja Mall', 'Delhi G...",Central garden full view.\nGood ventilation.\n...,"['7 Fan', '7 Light', '3 Wardrobe', 'No AC', 'N...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area5 out of 5', 'Amenities3 out of 5'..."

In [22]:
df.sample(5)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2264,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,sector 90,1.24,7065.0,1755.0,Super Built up area 1755(163.04 sq.m.)Built Up...,3,3,3+,others,"Top Floor, Sector 90 Gurgaon, Gurgaon, Haryana",9.0,South,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",Dlf regal garden sector 90Ready to move in pro...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4.5 out ..."
1540,3 BHK Flat in Dwarka Expressway Gurgaon,flat,hero homes,dwarka expressway,1.60,7825.0,2045.0,Super Built up area 1689(156.91 sq.m.),3,3,3,not available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Gol Market', 'Gurdwara Baba Deep Singh', 'Gu...",We are the proud owners of this 3 bhk apartmen...,"['2 Wardrobe', '2 Fan', '2 Light', '1 Modular ...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
188,1 Bedroom House for sale in Mianwali Colony,house,project mianwali colony,sector 12,1.70,9444.0,1800.0,Carpet area: 1800 (167.23 sq.m.),1,1,2,not available,"Mianwali Colony, Sector 12a, Mianwali Colony, ...",1.0,NaN,undefined,"['Hanuman Mandir', 'Sheetla Mata Mandir', 'Lal...",Best in class property available at mianwali c...,NaN,NaN,"['Environment3.5 out of 5', 'Lifestyle4 out of..."
1851,3 BHK Flat in Sector 89 A Gurgaon,flat,ats marigold,sector 89,1.50,8500.0,1765.0,Super Built up area 1750(162.58 sq.m.)Built Up...,3,3,3,not available,"Sector 89 A Gurgaon, Gurgaon, Haryana",5.0,North,Under Construction,"['Reliance Trends Newtown Square Mall', 'Dwark...","Oc is recieved. Beautiful , ready to possess u...","['1 Fan', '1 Light', '1 AC', '1 Modular Kitche...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
346,2 BHK Flat in Sector 81 Gurgaon,flat,signature global city 81,sector 81,0.80,14652.0,546.0,Carpet area: 546 (50.73 sq.m.),2,2,2,study room,"Sector 81 Gurgaon, Gurgaon, Haryana",4.0,North,Feb 2024,"['Ambience Mall New', 'Dwarka Expressway', 'NH...","Situated in sector-81 gurgaon, gurgaon, signat...","['3 Fan', 'No AC', 'No Bed', 'No Chimney', 'No...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Safety4.5 out of 5', 'Lifestyle4 out of 5', ..."

In [23]:
df.drop(columns=['property_name','address','description','rating'],inplace=True)

In [24]:
df.head()

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
0,flat,emaar mgf the palm drive,sector 66,3.98,18090.0,2200.0,Super Built up area 2200(204.39 sq.m.),3,4,3+,servant room,2.0,South-East,5 to 10 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","['6 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Power Back-up', 'In..."
1,flat,emaar digihomes,sector 62,2.15,14257.0,1508.0,Carpet area: 1508 (140.1 sq.m.),2,2,3,not available,31.0,NaN,Under Construction,"['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",NaN,"['Security / Fire Alarm', 'Intercom Facility',..."
2,flat,m3m heights,sector 65,2.44,13300.0,1835.0,Super Built up area 1828(169.83 sq.m.),3,3,2,not available,7.0,NaN,May 2024,"['Rapid Metro Sector 56', 'M3m 65th Avenue Mal...",[],"['Power Back-up', 'Intercom Facility', 'Lift(s..."
3,flat,the close south,sector 50,3.10,12444.0,2491.0,Super Built up area 2491(231.42 sq.m.)Built Up...,3,4,3+,servant room,4.0,North-East,5 to 10 Year Old,"['Fresco Market', 'Emerald Plaza', 'Tagore Pub...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'..."
4,flat,unitech the residences,sector 33,1.55,9872.0,1570.0,Super Built up area 1570(145.86 sq.m.),3,4,1,servant room,1.0,South,1 to 5 Year Old,"['Huda Metro Station', 'Raheja Mall', 'Delhi G...","['7 Fan', '7 Light', '3 Wardrobe', 'No AC', 'N...","['Security / Fire Alarm', 'Lift(s)', 'Maintena..."

In [25]:
df['sector'].value_counts()

sector
sohna road           163
sector 102           113
sector 85            110
sector 92            105
sector 69             94
sector 90             91
sector 65             90
sector 81             90
sector 109            88
sector 79             80
sector 33             74
sector 104            73
sector 83             69
sector 37d            68
sector 86             67
sector 43             67
sector 95             66
sector 50             65
sector 89             64
sector 2              63
sector 107            60
sector 108            59
sector 56             57
sector 48             56
sector 70a            54
sector 70             53
sector 37c            53
sector 84             51
sector 26             50
sector 4              49
sector 49             48
sector 67             48
sector 28             47
sector 66             46
sector 103            45
sector 3              44
sector 113            43
sector 25             43
sector 61             42
sector 82             42
sector 7              39
sector 106            38
sector 12             37
manesar               33
sector 99a            32
sector 54             31
sector 68             30
sector 77             29
sector 72             29
sector 71             27
sector 112            24
sector 110            24
sector 24             24
sector 57             24
sector 88a            23
sector 14             23
sector 105            23
sector 111            22
sector 67a            22
sector 11             21
sector 82a            20
sector 22             20
sector 78             19
sector 47             19
sector 74             18
gwal pahari           18
sector 63a            18
sector 62             17
sector 91             17
sector 99             16
sector 63             15
sector 76             15
sector 60             15
sector 53             14
sector 55             14
sector 52             14
sector 9              13
sector 46             13
sector 36a            13
sector 23             13
sector 6              13
sector 39             12
sohna road road       12
sector 31             12
sector 93             12
sector 38             12
sector 41             11
sector 9a             11
sector 36             11
sector 13             10
sector 45              9
sector 8               8
sector 17              8
sector 40              8
dwarka expressway      8
sector 59              8
sector 10a             8
sector 51              7
sector 58              7
sector 5               6
sector 21              6
sector 15              6
sector 1               6
sector 80              5
sector 30              5
sector 17a             3
sector 73              3
sector 88b             3
sector 17b             3
sector 27              3
sector 37              1
Name: count, dtype: int64

In [26]:
print(
    df[df['sector'].str.contains('sohna', case=False, na=False)][
        'sector'
    ].unique()
)

['sohna road' 'sohna road road']

In [27]:
df['sector'] = df['sector'].str.strip()

df['sector'] = df['sector'].str.replace(
    r'sohna\s+road\s+road', 'sohna road', case=False, regex=True
)

In [28]:
print(
    df['sector']
    .value_counts()[
        df['sector'].value_counts().index.str.contains('sohna', case=False)
    ]
)

sector
sohna road    175
Name: count, dtype: int64

In [29]:
df['sector'].value_counts()

sector
sohna road           175
sector 102           113
sector 85            110
sector 92            105
sector 69             94
sector 90             91
sector 65             90
sector 81             90
sector 109            88
sector 79             80
sector 33             74
sector 104            73
sector 83             69
sector 37d            68
sector 86             67
sector 43             67
sector 95             66
sector 50             65
sector 89             64
sector 2              63
sector 107            60
sector 108            59
sector 56             57
sector 48             56
sector 70a            54
sector 70             53
sector 37c            53
sector 84             51
sector 26             50
sector 4              49
sector 49             48
sector 67             48
sector 28             47
sector 66             46
sector 103            45
sector 3              44
sector 113            43
sector 25             43
sector 61             42
sector 82             42
sector 7              39
sector 106            38
sector 12             37
manesar               33
sector 99a            32
sector 54             31
sector 68             30
sector 77             29
sector 72             29
sector 71             27
sector 112            24
sector 110            24
sector 24             24
sector 57             24
sector 88a            23
sector 14             23
sector 105            23
sector 111            22
sector 67a            22
sector 11             21
sector 82a            20
sector 22             20
sector 78             19
sector 47             19
sector 74             18
gwal pahari           18
sector 63a            18
sector 62             17
sector 91             17
sector 99             16
sector 63             15
sector 76             15
sector 60             15
sector 53             14
sector 55             14
sector 52             14
sector 9              13
sector 46             13
sector 36a            13
sector 23             13
sector 6              13
sector 39             12
sector 31             12
sector 93             12
sector 38             12
sector 41             11
sector 9a             11
sector 36             11
sector 13             10
sector 45              9
sector 8               8
sector 17              8
sector 40              8
dwarka expressway      8
sector 59              8
sector 10a             8
sector 51              7
sector 58              7
sector 5               6
sector 21              6
sector 15              6
sector 1               6
sector 80              5
sector 30              5
sector 17a             3
sector 73              3
sector 88b             3
sector 17b             3
sector 27              3
sector 37              1
Name: count, dtype: int64

In [30]:
df.to_csv('dataset/gurgaon_properties_cleaned_v1.csv',index=False)